import Foundation

struct DefaultLang {
    static let LangValues = [
    "app_name":"SCIIL eLPA",
    "settings":"Settings",
    "remember":"Remember me",
    "login":"Login",
    "password":"Password",
    "user":"User",
    "title_activity_audit_list":"Audits List",
    "info":"Info",
    "filter":"Filter",
    "user_audit_list_item":"User:",
    "workstation_audit_list_item":"Workstation:",
    "planned_audit_list_item":"Planned:",
    "ok":"OK",
    "nok":"NOK",
    "photo":"Photo",
    "fixed":"Fixed",
    "machine":"Workstation",
    "from":"From",
    "to":"To",
    "wrong_password":"Wrong username or password",
    "server_problem":"Problem connecting to server",
    "status_planned":"Planned",
    "status_overdue":"Overdue",
    "status_not_synced":"Not Synced",
    "status_started":"Started",
    "status_not_finished":"Not Finished",
    "no_planned_audits":"No planned audits. Adjust filter settings",
    "save":"Save",
    "cancel":"Cancel",
    "do_not_save":"Do not save",
    "save_changes":"Do you want to save changes?",
    "audit_started_by":"The audit is already started by: ",
    "not_all_answers_have_comment":"Please add a comment next to false answers",
    "language":"Language",
    "back":"Back",
    "finished_uploading":"Finished uploading audits.",
    "select_language":"Language not selected. Please select language!",
    "server_url":"Profile server URL",
    "profile":"Profile",
    "could_not_download_profiles":"Could not download profiles",
    "uploading_audit":"Uploading audit…",
    "uploading_photos":"Uploading audit photos…",
    "finished_uploading_photos":"Finished uploading photos.",
    "can_not_open_audit_offline":"Cannot open audit. There is a problem connecting to server",
    "can_not_open_audit_no_questions":"Error on opening audit!",
    "connection_error":"Connection error",
    "close_app":"Close app",
    "error_saving_answers":"Error on saving audit!",
    "can_not_save_photo":"Can not save photos!",
    "delete":"Delete",
    "change":"Change",
    "yes": "YES",
    "no": "NO",
    "photo_delete_confirmation":"Photo will be deleted. Continue?",
    "invalid_web_service_url":"Invalid web service url",
    "no_internet_connection":"No internet connection",
    "logout":"Logout",
    "alert_choose_exit_option":"Please choose",
    "error":"Error!",
    "invalid_server_url":"Invalid server URL",
    "server_error":"Server error!",
    "filter_saved":"Filter saved!",
    "question_edit_text_hint":"Enter Text here",
    "select_module":"Select module",
    "photo_is_not_available":"Photo is not available"
    ]
}
